dd

In [23]:
a=3
b=4.3
p=" I am Sam."
x= True

In [24]:
a,b,p,x

(3, 4.3, ' I am Sam.', True)

In [25]:
range(5)

range(0, 5)

In [30]:
for n in range(5):
    print(n*10)

0
10
20
30
40


In [72]:
def my_f(b,d,a=100,c=20):      # function define
    print(a,b,c,d)
    
my_f(1000,1)

100 1000 20 1


In [77]:
a = "My name is"
b = "HongKilDong"
c = a+" "+b

In [82]:
d=123
e='123'
type(d),type(e)

(int, str)

In [83]:
a=[0,1,2,3,5]
b=[5,"girl",2+0j,"horse",21]

In [100]:
len(a),len(b)

(5, 5)

In [102]:
# use of range
a = range(0,10,2) # start, stop, step
print(a)

range(0, 10, 2)


In [103]:
for i in range(5):
    print(i)

0
1
2
3
4


In [105]:
for i in range(0,-10,-2):
    print(i)

0
-2
-4
-6
-8


# list

In [109]:
my_list=['one','two','three','four','five']
my_list_len=len(my_list)
for i in range(0,my_list_len):
    print(my_list[i])

one
two
three
four
five


In [159]:
aa = [1,2,3.4,'abc']
array_aa = np.array(aa)
aa, array_aa

([1, 2, 3.4, 'abc'], array(['1', '2', '3.4', 'abc'], dtype='<U32'))

# tuples

In [112]:
c=(1,2,3,4,5)
c[4]

5

# multidimensional list

In [114]:
a=[[1,2,3],[4,5,6]]

In [120]:
type(a)

list

In [125]:
import numpy as np
array_a=np.array(a)

In [127]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [139]:
array_a[0]

array([1, 2, 3])

list slicing

In [141]:
a

[[1, 2, 3], [4, 5, 6]]

In [148]:
np.array(a)[1,2]

6

In [150]:
a[-2:]

[[1, 2, 3], [4, 5, 6]]

# 1-D array

In [153]:
import numpy as np

In [155]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [161]:
b=[0,1,2,3,4,5,6,7,8,9]
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [163]:
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
a[3:9:2], b[3:9:2]

(array([3, 5, 7]), [3, 5, 7])

In [169]:
a+a, b+b

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#2-d array examples

In [174]:
data = np.array([[11,22,0],[44,55,1],[77,88,1]])
data

array([[11, 22,  0],
       [44, 55,  1],
       [77, 88,  1]])

In [177]:
X, y = data[:,:-1],data[:,-1]

In [180]:
X,y

(array([[11, 22],
        [44, 55],
        [77, 88]]), array([0, 1, 1]))

In [182]:
X[0]

array([11, 22])

In [212]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [213]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [230]:
c = np.arange(6)
c = c.reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [231]:
b = np.array(b)
b = b.reshape(5,2)
b, c

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([[0, 1, 2],
        [3, 4, 5]]))

# Title 1
## title 2
### title 3
- arrays can also be created by Numpy function

In [184]:
np.linspace(0,10,5) # start, end, no of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [186]:
np.linspace(0,10) # default : 50개

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [189]:
np.logspace(1,3,3)

array([  10.,  100., 1000.])

In [192]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [194]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [196]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [202]:
a = np.linspace(-1,5,7) # -1부터 5까지 7번 찍어라
a*6, a/5, a+4, a-10, np.sin(a), np.exp(-a)

(array([-6.,  0.,  6., 12., 18., 24., 30.]),
 array([-0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]),
 array([3., 4., 5., 6., 7., 8., 9.]),
 array([-11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.]),
 array([-0.84147098,  0.        ,  0.84147098,  0.90929743,  0.14112001,
        -0.7568025 , -0.95892427]),
 array([2.71828183, 1.        , 0.36787944, 0.13533528, 0.04978707,
        0.01831564, 0.00673795]))

In [204]:
# exercise : create x-y dataset of y=cos(x) vs. x over interval (-pi,+pi)
x = np.linspace(-3.14,+3.14,21)
y = np.cos(x)
x,y

(array([-3.14 , -2.826, -2.512, -2.198, -1.884, -1.57 , -1.256, -0.942,
        -0.628, -0.314,  0.   ,  0.314,  0.628,  0.942,  1.256,  1.57 ,
         1.884,  2.198,  2.512,  2.826,  3.14 ]),
 array([-9.99998732e-01, -9.50612598e-01, -8.08267427e-01, -5.86882949e-01,
        -3.08108031e-01,  7.96326711e-04,  3.09622813e-01,  5.88171730e-01,
         8.09204181e-01,  9.51105720e-01,  1.00000000e+00,  9.51105720e-01,
         8.09204181e-01,  5.88171730e-01,  3.09622813e-01,  7.96326711e-04,
        -3.08108031e-01, -5.86882949e-01, -8.08267427e-01, -9.50612598e-01,
        -9.99998732e-01]))

# dictionary

In [235]:
room = {"Kim":271, "Hong":362, "Lee":876}
type(room)

dict

In [240]:
room["Lee"]

876

In [254]:
d["last_name"] = "Kim"
d["first_name"] = "Hogun"
d["birth_day"] = "january 21"
d

TypeError: 'int' object does not support item assignment

# random number generation

In [266]:
np.random.rand(10) # uniform distribution in [0,1]

array([0.4163666 , 0.06896349, 0.74497438, 0.56010187, 0.58559806,
       0.88954785, 0.10512864, 0.67920994, 0.18790842, 0.41306877])

In [267]:
# uniform distribution in (10,20)
a,b=10,20
(b-a)*np.random.rand(10)+a

array([14.24056453, 16.32252933, 13.72554848, 17.78673012, 12.93760987,
       19.20242845, 15.45790685, 18.63967172, 18.48820108, 17.07783593])

In [269]:
np.random.randn(10) # mean = 0, sigma = 1 

array([ 7.60730821e-01, -5.08569454e-01,  1.70815367e-01, -3.76092841e-01,
       -3.27533868e-01, -3.13666243e-01,  3.52085738e-04,  2.68385520e-01,
        1.36969827e+00, -1.89366450e-01])

In [273]:
# normal distribution with mean = 15, sigma = 10
x0,sigma=15,10
sigma*np.random.randn(20) + x0

array([33.05213306, 11.12228263,  8.48108379, 23.93533834, 37.62026684,
       -2.61756559, 30.30433198, 16.76984476, 23.80389943, -7.92305915,
        5.94305679, 16.76276846,  7.4194992 ,  3.99251569, 20.27664136,
        4.182086  , 20.73036181, -7.82773622, 13.06005001, -0.28690218])

In [275]:
np.random.randint(1,7,12)

array([6, 2, 4, 5, 5, 5, 5, 3, 1, 2, 5, 4])

# call by what?

In [290]:
def test(a):             #
    a=2

In [292]:
a=1
test(a)
a

1

In [297]:
def test2(a):            # looks like call by reference
    a.append("World.")

In [299]:
b=["Hello"]
test2(b)
b

['Hello', 'World.']

In [303]:
# call by object

a=10
b=a
a+=100
a,b,id(a), id(b) # id가 다름 / 하나만 바뀜 ( 바꿀 수 없으니, 새로운걸 만듬.)

(110, 10, 140708666801312, 140708666798112)

In [307]:
a=[1,2,3]
b=a
a+=[4,5,6]
a,b, id(a), id(b) # 같은 id라 같이 바뀜 ( list : mutable은 바꿀 수 있으니까 새로운걸 안만듬. 똑같은걸 사용.)

([1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6], 2719394667848, 2719394667848)

In [310]:
!dir

 C 드라이브의 볼륨: OS
 볼륨 일련 번호: A28A-1A03

 C:\Users\Admin 디렉터리

2019-02-18  오후 04:16    <DIR>          .
2019-02-18  오후 04:16    <DIR>          ..
2018-11-28  오후 03:28    <DIR>          .anaconda
2019-02-18  오후 04:16    <DIR>          .conda
2019-02-18  오전 10:54                43 .condarc
2018-12-21  오후 01:05    <DIR>          .idlerc
2019-02-18  오후 01:50    <DIR>          .ipynb_checkpoints
2018-11-28  오후 03:32    <DIR>          .ipython
2019-02-18  오후 01:27    <DIR>          .jupyter
2018-11-26  오후 04:38    <DIR>          .vscode
2019-02-08  오후 02:10    <DIR>          3D Objects
2018-11-28  오후 02:47                 0 a
2019-02-18  오후 01:34    <DIR>          Anaconda3
2019-02-08  오후 02:10    <DIR>          Contacts
2019-02-08  오후 02:10    <DIR>          Desktop
2019-02-08  오후 02:10    <DIR>          Documents
2019-02-18  오전 10:56    <DIR>          Downloads
2019-02-08  오후 02:10    <DIR>          Favorites
2019-02-18  오후 01:28                 0 intro1
2019-02-08  오후 02:10    <DIR>         

### fandas DataFrame

In [329]:
import pandas as pd
import numpy as np
n = np.random.randn(6) # 1-d array
n2 = n.reshape(2,3)    # 2-d array
n, n2

(array([ 1.20509934, -0.27322439,  1.62325103,  0.10085488, -0.27942798,
         0.74754029]), array([[ 1.20509934, -0.27322439,  1.62325103],
        [ 0.10085488, -0.27942798,  0.74754029]]))

In [334]:
s1 = pd.Series(n, index=['a','b','c','d','e','f'])
s1

a    1.205099
b   -0.273224
c    1.623251
d    0.100855
e   -0.279428
f    0.747540
dtype: float64

In [335]:
s2 = pd.DataFrame(n2,columns=['a','b','c'])
s2

a         b         c
0  1.205099 -0.273224  1.623251
1  0.100855 -0.279428  0.747540

In [338]:
type(s1), type(s2)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [342]:
s2.index

RangeIndex(start=0, stop=2, step=1)

In [344]:
s1

a    1.205099
b   -0.273224
c    1.623251
d    0.100855
e   -0.279428
f    0.747540
dtype: float64

In [347]:
s1[0], s1['a']

(1.2050993398272727, 1.2050993398272727)

In [350]:
s1.median(), s1.mean()

(0.42419758338387764, 0.520682193440931)

In [354]:
sss = s1[s1>s1.median()]
sss

a    1.205099
c    1.623251
f    0.747540
dtype: float64

In [359]:
s1[1:]

b   -0.273224
c    1.623251
d    0.100855
e   -0.279428
f    0.747540
dtype: float64

In [361]:
s1[:-1]

a    1.205099
b   -0.273224
c    1.623251
d    0.100855
e   -0.279428
dtype: float64

In [363]:
s1[1:]+s1[:-1]

a         NaN
b   -0.546449
c    3.246502
d    0.201710
e   -0.558856
f         NaN
dtype: float64

In [365]:
s = pd.Series(np.random.randn(5),name="Dummy")
s

0   -1.450966
1    1.922737
2   -0.202530
3    0.934540
4   -1.059741
Name: Dummy, dtype: float64

In [367]:
s.name

'Dummy'

In [369]:
d = {'one':[1,2,3,4], 'two':[4,3,2,1]}

In [371]:
d

{'one': [1, 2, 3, 4], 'two': [4, 3, 2, 1]}

In [376]:
df = pd.DataFrame(d)
df

one  two
0    1    4
1    2    3
2    3    2
3    4    1

In [380]:
df['one'],type(df['one'])

(0    1
 1    2
 2    3
 3    4
 Name: one, dtype: int64, pandas.core.series.Series)

In [382]:
df['three']=df['one']+df['two'] # three라는 칼럼 생성
df

one  two  three
0    1    4      5
1    2    3      5
2    3    2      5
3    4    1      5

In [404]:
df.drop(['three'],axis=1) # three라는 칼럼 제거

one  bar  two  one_trnc
0    1    1  bar       1.0
1    2    2  bar       2.0
2    3    3  bar       NaN
3    4    4  bar       NaN

In [406]:
df.drop([2],axis=0)

one  bar  three  two  one_trnc
0    1    1      5  bar       1.0
1    2    2      5  bar       2.0
3    4    4      5  bar       NaN

In [408]:
df

one  bar  three  two  one_trnc
0    1    1      5  bar       1.0
1    2    2      5  bar       2.0
2    3    3      5  bar       NaN
3    4    4      5  bar       NaN

In [410]:
df['two']='bar'
df

one  bar  three  two  one_trnc
0    1    1      5  bar       1.0
1    2    2      5  bar       2.0
2    3    3      5  bar       NaN
3    4    4      5  bar       NaN

In [412]:
df['one_trnc']=df['one'][:2]
df

one  bar  three  two  one_trnc
0    1    1      5  bar       1.0
1    2    2      5  bar       2.0
2    3    3      5  bar       NaN
3    4    4      5  bar       NaN

In [419]:
df

one  bar  three  two  one_trnc
0    1    1      5  bar       1.0
1    2    2      5  bar       2.0
2    3    3      5  bar       NaN
3    4    4      5  bar       NaN

In [421]:
df.insert(2,'bar4',df['one']) # col 이름이 중복되면 안됨.
df

one  bar  bar4  bar3  three  two  one_trnc
0    1    1     1     1      5  bar       1.0
1    2    2     2     2      5  bar       2.0
2    3    3     3     3      5  bar       NaN
3    4    4     4     4      5  bar       NaN

In [424]:
np.random.randn(10,4)

array([[ 0.5070391 ,  2.26293543,  1.64215437,  0.66290767],
       [ 0.45605933,  0.44715768, -0.74327983, -0.54654656],
       [ 0.73883152,  0.13728899,  0.17349234, -1.12618913],
       [-0.52497024,  0.7699643 , -2.10732042, -0.22232364],
       [-0.66535286,  0.27777366, -0.93872577,  1.37063136],
       [-0.28677902, -0.31889531,  0.2008891 ,  0.7065196 ],
       [-0.94668479, -1.0110869 ,  0.76762322, -0.33858735],
       [ 0.39827826,  0.95874267,  0.84715071, -0.78401159],
       [ 0.57144114, -0.74383544,  1.88843029, -0.33379629],
       [ 1.24364474, -0.34059783, -1.35319609,  0.09382573]])

In [426]:
df = pd.DataFrame(np.random.randn(10,4),columns=['A','B','C','D'])
df

A         B         C         D
0 -1.535232 -0.504096  0.798272 -1.789776
1 -0.043114 -0.000092  0.084030 -0.393845
2  1.097518  0.687373 -0.695697 -1.721429
3 -1.067890 -1.804519  0.212201 -0.533104
4 -0.355864  0.059248  0.408891  0.933690
5 -0.509452  0.158203  0.180755 -0.604736
6 -0.942623 -0.596365  1.651615  0.779522
7  0.624598  0.565543 -1.632934  0.753844
8  0.302562 -0.716661  1.643929 -1.058504
9  2.507943 -0.012074 -0.465220 -0.320476

In [428]:
df.T

0         1         2         3         4         5         6  \
A -1.535232 -0.043114  1.097518 -1.067890 -0.355864 -0.509452 -0.942623   
B -0.504096 -0.000092  0.687373 -1.804519  0.059248  0.158203 -0.596365   
C  0.798272  0.084030 -0.695697  0.212201  0.408891  0.180755  1.651615   
D -1.789776 -0.393845 -1.721429 -0.533104  0.933690 -0.604736  0.779522   

          7         8         9  
A  0.624598  0.302562  2.507943  
B  0.565543 -0.716661 -0.012074  
C -1.632934  1.643929 -0.465220  
D  0.753844 -1.058504 -0.320476

In [431]:
np.exp(df)

A         B         C         D
0   0.215406  0.604051  2.221699  0.166998
1   0.957802  0.999908  1.087662  0.674459
2   2.996719  1.988486  0.498727  0.178810
3   0.343733  0.164554  1.236396  0.586781
4   0.700568  1.061038  1.505148  2.543879
5   0.600825  1.171404  1.198121  0.546219
6   0.389605  0.550810  5.215398  2.180431
7   1.867496  1.760404  0.195355  2.125154
8   1.353322  0.488380  5.175464  0.346975
9  12.279640  0.987998  0.627997  0.725804

In [433]:
df_array = np.asarray(df)
df, df_array

(          A         B         C         D
 0 -1.535232 -0.504096  0.798272 -1.789776
 1 -0.043114 -0.000092  0.084030 -0.393845
 2  1.097518  0.687373 -0.695697 -1.721429
 3 -1.067890 -1.804519  0.212201 -0.533104
 4 -0.355864  0.059248  0.408891  0.933690
 5 -0.509452  0.158203  0.180755 -0.604736
 6 -0.942623 -0.596365  1.651615  0.779522
 7  0.624598  0.565543 -1.632934  0.753844
 8  0.302562 -0.716661  1.643929 -1.058504
 9  2.507943 -0.012074 -0.465220 -0.320476,
 array([[-1.53523230e+00, -5.04096170e-01,  7.98272212e-01,
         -1.78977558e+00],
        [-4.31141086e-02, -9.19862652e-05,  8.40301273e-02,
         -3.93844836e-01],
        [ 1.09751819e+00,  6.87373338e-01, -6.95696512e-01,
         -1.72142905e+00],
        [-1.06789045e+00, -1.80451942e+00,  2.12200791e-01,
         -5.33104216e-01],
        [-3.55864244e-01,  5.92478610e-02,  4.08891240e-01,
          9.33689953e-01],
        [-5.09452301e-01,  1.58203226e-01,  1.80754785e-01,
         -6.04735951e-01],
    

In [435]:
df.head()

A         B         C         D
0 -1.535232 -0.504096  0.798272 -1.789776
1 -0.043114 -0.000092  0.084030 -0.393845
2  1.097518  0.687373 -0.695697 -1.721429
3 -1.067890 -1.804519  0.212201 -0.533104
4 -0.355864  0.059248  0.408891  0.933690

In [437]:
df.head(10)

A         B         C         D
0 -1.535232 -0.504096  0.798272 -1.789776
1 -0.043114 -0.000092  0.084030 -0.393845
2  1.097518  0.687373 -0.695697 -1.721429
3 -1.067890 -1.804519  0.212201 -0.533104
4 -0.355864  0.059248  0.408891  0.933690
5 -0.509452  0.158203  0.180755 -0.604736
6 -0.942623 -0.596365  1.651615  0.779522
7  0.624598  0.565543 -1.632934  0.753844
8  0.302562 -0.716661  1.643929 -1.058504
9  2.507943 -0.012074 -0.465220 -0.320476

In [441]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [443]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [445]:
df.values

array([[-1.53523230e+00, -5.04096170e-01,  7.98272212e-01,
        -1.78977558e+00],
       [-4.31141086e-02, -9.19862652e-05,  8.40301273e-02,
        -3.93844836e-01],
       [ 1.09751819e+00,  6.87373338e-01, -6.95696512e-01,
        -1.72142905e+00],
       [-1.06789045e+00, -1.80451942e+00,  2.12200791e-01,
        -5.33104216e-01],
       [-3.55864244e-01,  5.92478610e-02,  4.08891240e-01,
         9.33689953e-01],
       [-5.09452301e-01,  1.58203226e-01,  1.80754785e-01,
        -6.04735951e-01],
       [-9.42622990e-01, -5.96365479e-01,  1.65161542e+00,
         7.79522362e-01],
       [ 6.24598485e-01,  5.65543420e-01, -1.63293449e+00,
         7.53844040e-01],
       [ 3.02562322e-01, -7.16660564e-01,  1.64392902e+00,
        -1.05850398e+00],
       [ 2.50794260e+00, -1.20741646e-02, -4.65220017e-01,
        -3.20475841e-01]])

In [447]:
df.describe()

A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.007845  -0.216344   0.218584  -0.395481
std     1.190204   0.725153   1.011525   0.981972
min    -1.535232  -1.804519  -1.632934  -1.789776
25%    -0.834330  -0.573298  -0.327907  -0.945062
50%    -0.199489  -0.006083   0.196478  -0.463475
75%     0.544089   0.133464   0.700927   0.485264
max     2.507943   0.687373   1.651615   0.933690

In [449]:
df[0:3]

A         B         C         D
0 -1.535232 -0.504096  0.798272 -1.789776
1 -0.043114 -0.000092  0.084030 -0.393845
2  1.097518  0.687373 -0.695697 -1.721429

In [452]:
df.drop('A',axis=1,inplace=True),df # A col 없앰.

(None,           B         C         D
 0 -0.504096  0.798272 -1.789776
 1 -0.000092  0.084030 -0.393845
 2  0.687373 -0.695697 -1.721429
 3 -1.804519  0.212201 -0.533104
 4  0.059248  0.408891  0.933690
 5  0.158203  0.180755 -0.604736
 6 -0.596365  1.651615  0.779522
 7  0.565543 -1.632934  0.753844
 8 -0.716661  1.643929 -1.058504
 9 -0.012074 -0.465220 -0.320476)

## exercise for Class

In [456]:
class myClass:
    """This is an eample class for Python.""" #doc (안넣어도됨.)
    def __init__ (self): #init : 생성자
        self.data = {'1','2'}
    i = 235
    def j (self):
        return('Hello, How are you')

In [458]:
x = myClass()

In [461]:
x.i

235

In [463]:
x.j()

'Hello, How are you'

In [465]:
x.data

{'1', '2'}

In [467]:
x.__doc__

'This is an eample class for Python.'